### ISSUE TITLE
Editing occurrence of recurring event broken

### ISSUE THREAD

**Issue by kylecombes** [olinlibrary/abe-web-frontend#39] opened 2017-07-17 14:09 UTC
## Steps to reproduce
  * Click on recurring event in calendar view, click *Edit occurrence*
  * Change date, description, and labels.
  * Click *Update Event*

## Observed problems
  * Description changed for all occurrences
  * Date not changed
  * Tags gone
  * Can't edit again because `seriesData` is not set

**Comment by audreywl** [comment] 2017-07-17 18:02
Could not reproduce this specifically, probably because we fixed the label issue first. Did find another timezones bug though, goddammit. Leaving this open for a bit in case we run into it again.

**Comment by audreywl** [comment] 2017-07-24 13:46
Still haven't run into this again, closing.

**Closed by audreywl** 2017-07-24 13:46 UTC
Labels: bug
